"""Optional, bounded registration with locally installed agent CLIs.

The agent's own CLI remains the owner of its configuration file. This module
only invokes an official CLI with an argument vector: it never edits JSON/TOML,
passes credentials, enables shell interpretation, or prints process output.

Codex's verified ``mcp list --json`` inventory is the only registration probe.
The expected output is a JSON list of named server objects with a ``transport``
object. A matching SignalWeave entry must be enabled stdio with the exact
command and args generated by :func:`agent_config`, and with empty env/env_vars.
Anything malformed, ambiguous, disabled, or different is manual/conflict; it
is never replaced. Claude Code registration uses its official ``claude mcp
add`` command when the user explicitly asks SignalWeave to connect it. The
module never edits Claude's configuration file directly; a missing CLI or a
non-zero command keeps the setup intact and prints the exact command for manual
completion.

The official CLI operation is bounded but not race-free. Users should close
concurrent Codex config editors while registration runs.
"""

from __future__ import annotations

import json
import os
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

from .local_setup import SetupError, agent_config, agent_registration, resolve_home

_TIMEOUT_SECONDS = 5.0
_CREDENTIAL_NAMES = {
    "TYPESAFE_API_KEY", "PRESET_ACCESS_TOKEN", "PRESET_API_TOKEN_NAME", "PRESET_API_TOKEN_SECRET",
    "SIGNALWEAVE_API_TOKEN", "PUSH_WEBHOOK_TOKEN", "SUPERSET_PASSWORD", "MCP_BEARER_TOKEN",
    "MCP_API_TOKEN", "MCP_API_KEY",
}
_CREDENTIAL_NAMES.update(f"{name}_FILE" for name in tuple(_CREDENTIAL_NAMES))
Outcome = Literal[
    "registered", "already_configured", "manual_required", "conflict", "unavailable", "failed",
]


@dataclass(frozen=True)
class AgentRegistrationStatus:
    """Secret-free result of an optional registration attempt."""

    agent: str
    outcome: Outcome
    message: str
    command: str | None = None

    @property
    def changed(self) -> bool:
        return self.outcome == "registered"


def _entry(home: Path) -> tuple[str, list[str]]:
    value = json.loads(agent_config(home, "claude"))
    server = value["mcpServers"]["signalweave"]
    return server["command"], list(server["args"])


def _safe_environment() -> dict[str, str]:
    """Keep agent/runtime settings while removing SignalWeave source secrets."""
    return {name: value for name, value in os.environ.items() if name not in _CREDENTIAL_NAMES}


def _run(argv: list[str]) -> subprocess.CompletedProcess[str]:
    """Run an agent CLI with a bounded timeout and scrubbed environment."""
    return subprocess.run(
        argv, check=False, capture_output=True, text=True, timeout=_TIMEOUT_SECONDS,
        shell=False, stdin=subprocess.DEVNULL, env=_safe_environment(),
    )


def _command(home: Path, agent: str) -> str:
    return agent_registration(home, agent)


def _inventory(result: subprocess.CompletedProcess[str]) -> tuple[str, list[dict[str, Any]]] | AgentRegistrationStatus:
    """Parse only the bounded, documented JSON shape; never echo CLI output."""
    if result.returncode != 0:
        return AgentRegistrationStatus("codex", "unavailable", f"codex inventory returned {result.returncode}")
    try:
        value = json.loads(result.stdout)
    except (TypeError, json.JSONDecodeError):
        return AgentRegistrationStatus("codex", "unavailable", "codex returned malformed MCP inventory")
    if not isinstance(value, list):
        return AgentRegistrationStatus("codex", "unavailable", "codex returned an invalid MCP inventory")
    items: list[dict[str, Any]] = []
    names: set[str] = set()
    for item in value:
        if not isinstance(item, dict) or not isinstance(item.get("name"), str):
            return AgentRegistrationStatus("codex", "unavailable", "codex returned an invalid MCP inventory item")
        name = item["name"]
        if name in names:
            return AgentRegistrationStatus("codex", "unavailable", "codex returned an ambiguous MCP inventory")
        names.add(name)
        items.append(item)
    return "ok", items


def _matches(item: dict[str, Any], executable: str, args: list[str]) -> bool:
    transport = item.get("transport")
    if not isinstance(transport, dict):
        return False
    return (
        item.get("enabled") is True and transport.get("type") == "stdio"
        and transport.get("command") == executable and transport.get("args") == args
        and transport.get("env") in (None, {}) and transport.get("env_vars", []) == []
        and transport.get("cwd") is None and item.get("cwd") is None
        and transport.get("enabled_tools", []) in (None, [])
        and transport.get("disabled_tools", []) in (None, [])
        and item.get("enabled_tools", []) in (None, [])
        and item.get("disabled_tools", []) in (None, [])
    )


def _codex_status(root: Path, command: str) -> AgentRegistrationStatus:
    executable, args = _entry(root)
    try:
        result = _run(["codex", "mcp", "list", "--json"])
    except FileNotFoundError:
        return AgentRegistrationStatus("codex", "unavailable", "codex CLI was not found", command)
    except subprocess.TimeoutExpired:
        return AgentRegistrationStatus("codex", "unavailable", "codex inventory check timed out", command)
    except (OSError, UnicodeError):
        return AgentRegistrationStatus("codex", "unavailable", "codex inventory check could not run", command)

    parsed = _inventory(result)
    if isinstance(parsed, AgentRegistrationStatus):
        return AgentRegistrationStatus("codex", parsed.outcome, parsed.message, command)
    _, items = parsed
    matches = [item for item in items if item["name"] == "signalweave"]
    if not matches:
        return AgentRegistrationStatus("codex", "manual_required", "codex has no signalweave entry", command)
    if _matches(matches[0], executable, args):
        return AgentRegistrationStatus("codex", "already_configured", "SignalWeave is already configured in Codex", command)
    return AgentRegistrationStatus(
        "codex", "conflict", "Codex has a different, disabled, or credential-bearing signalweave entry", command
    )


def read_agent_status(home: str | Path | None, agent: str) -> AgentRegistrationStatus:
    """Read conservative registration status without changing agent config."""
    if agent not in {"codex", "claude"}:
        raise SetupError("Unknown agent; choose codex or claude")
    root = resolve_home(home)
    command = _command(root, agent)
    if agent == "claude":
        return AgentRegistrationStatus(
            agent, "manual_required", "Claude Code status detection is left manual to protect existing MCP entries", command
        )
    return _codex_status(root, command)


def register_agent(home: str | Path | None, agent: str) -> AgentRegistrationStatus:
    """Register through a safe official CLI path, or return manual guidance."""
    if agent not in {"codex", "claude"}:
        raise SetupError("Unknown agent; choose codex or claude")
    root = resolve_home(home)
    command = _command(root, agent)
    if agent == "claude":
        executable, args = _entry(root)
        try:
            result = _run([
                "claude", "mcp", "add", "--transport", "stdio", "--scope", "user",
                "signalweave", "--", executable, *args,
            ])
        except FileNotFoundError:
            return AgentRegistrationStatus(agent, "unavailable", "claude CLI was not found", command)
        except subprocess.TimeoutExpired:
            return AgentRegistrationStatus(agent, "failed", "claude registration timed out", command)
        except (OSError, UnicodeError):
            return AgentRegistrationStatus(agent, "failed", "claude registration could not run", command)
        if result.returncode != 0:
            return AgentRegistrationStatus(
                agent,
                "conflict" if result.returncode == 1 else "failed",
                "claude did not register SignalWeave; an existing entry may need review",
                command,
            )
        return AgentRegistrationStatus(agent, "registered", "SignalWeave registered in Claude Code", command)

    status = _codex_status(root, command)
    if status.outcome != "manual_required":
        return status
    executable, args = _entry(root)
    try:
        result = _run(["codex", "mcp", "add", "signalweave", "--", executable, *args])
    except FileNotFoundError:
        return AgentRegistrationStatus(agent, "unavailable", "codex CLI was not found", command)
    except subprocess.TimeoutExpired:
        return AgentRegistrationStatus(agent, "failed", "codex registration timed out", command)
    except (OSError, UnicodeError):
        return AgentRegistrationStatus(agent, "failed", "codex registration could not run", command)
    if result.returncode != 0:
        return AgentRegistrationStatus(agent, "failed", f"codex registration returned {result.returncode}", command)

    verified = _codex_status(root, command)
    if verified.outcome == "already_configured":
        return AgentRegistrationStatus(agent, "registered", "SignalWeave registered and verified in Codex", command)
    return AgentRegistrationStatus(agent, "failed", "codex registration completed but verification failed", command)


__all__ = ["AgentRegistrationStatus", "read_agent_status", "register_agent"]
